### ISSUE TITLE
remote bme680

### ISSUE THREAD

**Issue by sdmydbr9** [seb-ma/MMM-Bosch-BME680-sensor#1]
hi, this module looks beautiful and im trying to implement it in my mirror as well, however my set up is little different, since my raspberry pi is already fitted inside the frame. i have a pico attached to bme680 sensor, and the data is being pushed using mqtt and im visualising the data in homebridge. would you consider adding a feature which would make it possible to use remote bme680 sensor to this module. i have looked into mqtt module as well and decided to give yours a try.

**Comment by seb-ma** [comment]
Hi,
I'm OK to improve this module (and I would be pleased to have happy users of my modules), but in my opinion, your request doesn't deserve this module.

This module is essentially designed to retrieve sensor data (the hard part) and to provide this data to other modules specifically designed to display weather information (by sending notifications).
The fact that this module can display information by itself is more like a bonus.

Regarding the code, using external data (like events from mqtt) would be equivalent to only keep the njk and css files of this module (the easy part).
So, instead of modifying this module I will go on a fresh new and very simple module designed to listen to events and display them (using my njk/css files if you like the display).

**Comment by sdmydbr9** [comment]
thanks for the quick response and suggestions, i will try to point myself in that direction. cheers.
